Repository lnovitz/jobseeker-analytics, pull requests merged in 2025-03, with the labels that each got.

#235 install missing dependencies for fe tests
  frontend/package-lock.json
  frontend/package.json
Labels: 🤖 aspect: dx, size:XS

#234 Routing fixes
  backend/login/google_login.py
  backend/main.py
  frontend/utils/navbar-utils.ts
Labels: 🛠 goal: fix, size:M

#237 add next step and interview emails
  backend/email_query_filters/applied_email_filter.yaml
  backend/tests/test_constants.py
  backend/tests/test_filter_schema.py
Labels: ⭐ goal: addition, size:L

#171 Create company_jobs.py
  backend/db/company_jobs.py
Labels: size:S, lgtm

#179 Create User Jobs Model
  backend/db/user_jobs.py
Labels: size:S, lgtm

#176 Create job_status.py
  backend/db/job_status.py
Labels: size:XS, lgtm

#178 Create Users Model
  backend/db/users.py
Labels: size:XS, lgtm

#257 run db in container and local
  CONTRIBUTING.md
  backend/.env.example
  backend/config.py
  backend/main.py
  docker-compose.yaml
Labels: 💻 aspect: code, size:M, lgtm

#238 Created UserSession model
  backend/db/user_session.py
Labels: ⭐ goal: addition, size:S, lgtm

#254 Database local setup
  .github/workflows/pytest.yml
  CONTRIBUTING.md
  backend/.env.example
  backend/config.py
  backend/db/init.sql
  backend/main.py
  backend/requirements.txt
  docker-compose.yaml
  frontend/.env.sample
  frontend/Dockerfile
  frontend/app/playground/page.tsx
  frontend/next.config.js
  frontend/package-lock.json
  frontend/package.json
Labels: ⭐ goal: addition, 📖 aspect: docs, size:L

#250 Save email data
  backend/config.py
  backend/db/user_email.py
  backend/db/utils/user_email_utils.py
  backend/login/google_login.py
  backend/main.py
Labels: ⭐ goal: addition, size:L, lgtm

#239 added relevant links to navbar "menu"
  frontend/components/icons.tsx
  frontend/components/navbar.tsx
  frontend/components/theme-switch.tsx
  frontend/tests/navbar.test.ts
Labels: 🛠 goal: fix, 🕹 aspect: interface, size:L

#260 trigger frontend workflow only when frontend files are changed
  .github/workflows/frontend-checks.yml
Labels: ✨ goal: improvement, 🤖 aspect: dx, size:XS

#258 conditional cookies noms
  backend/config.py
  backend/login/google_login.py
  backend/main.py
  backend/session/session_layer.py
  backend/tests/test_config_utils.py
  backend/utils/cookie_utils.py
Labels: 🛠 goal: fix, size:L, lgtm

#259 Create new user
  backend/.env.example
  backend/db/users.py
  backend/db/utils/user_utils.py
  backend/login/google_login.py
  backend/main.py
  backend/utils/auth_utils.py
Labels: ⭐ goal: addition, size:L, lgtm

#261 Fetch from user email
  backend/main.py
Labels: size:M, lgtm

#249 Dashboard Page
  .gitignore
  backend/main.py
  frontend/app/dashboard/page.tsx
  frontend/tests/dashboard.test.ts
Labels: ⭐ goal: addition, 🕹 aspect: interface, size:L, lgtm

#262 Fix backend code
  backend/main.py
  backend/session/session_layer.py
Labels: 🛠 goal: fix, 💻 aspect: code, size:S

#263 fix routing
  frontend/app/processing/page.tsx
Labels: 🛠 goal: fix, size:XS

#264 edit frontend to match what backend returns to display email sender
  frontend/app/dashboard/page.tsx
Labels: size:XS, lgtm

#204 Spinner Tests PR
  frontend/components/spinner.tsx
  frontend/tests/spinner.test.ts
Labels: 💻 aspect: code, size:S

#273 code cleanup/refactoring (focused on testing/playground related code)
  backend/database.py
  backend/db/test_model.py
  backend/main.py
  backend/routes/google_login.py
  backend/routes/playground_routes.py
  frontend/app/playground/page.tsx
Labels: 🤖 aspect: dx, size:L, lgtm

#292 Create routes/auth.py for login and logout functionality
  backend/main.py
  backend/routes/auth.py
Labels: 💻 aspect: code, size:S, lgtm

#265 Docker updates
  CONTRIBUTING.md
  docker-compose-dev.yaml
  frontend/Dockerfile.dev
  frontend/components/counter.tsx
Labels: ⭐ goal: addition, 📖 aspect: docs, size:M, lgtm

#298 create email_routes.py for code refactor
  backend/db/utils/user_utils.py
  backend/main.py
  backend/routes/auth_routes.py
  backend/routes/email_routes.py
Labels: 💻 aspect: code, size:L, lgtm

#300 chore: update email_utils.py
  backend/utils/email_utils.py
Labels: 💻 aspect: code, size:XS, lgtm

#301 Refactor fixes
  backend/database.py
  backend/main.py
  backend/routes/email_routes.py
Labels: size:M, lgtm

#302 Add missing download csv button
  backend/main.py
  backend/requirements.txt
  backend/routes/file_routes.py
  frontend/app/dashboard/page.tsx
  frontend/app/providers.tsx
  frontend/components/icons.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: ⭐ goal: addition, 🛠 goal: fix, size:L

#305 Update ESLint to the new modern flat config system woooooo
  .gitignore
  frontend/.eslintignore
  frontend/.eslintrc.json
  frontend/Dockerfile
  frontend/app/dashboard/page.tsx
  frontend/app/logout/page.tsx
  frontend/app/playground/page.tsx
  frontend/app/processing/page.tsx
  frontend/components/theme-switch.tsx
  frontend/eslint.config.mjs
  frontend/package-lock.json
  frontend/package.json
  frontend/tests/dashboard.test.ts
  package-lock.json
  package.json
Labels: 💻 aspect: code, 🤖 aspect: dx, size:L

#309 Track job title
  backend/db/user_email.py
  backend/db/utils/user_email_utils.py
  backend/routes/email_routes.py
  backend/utils/llm_utils.py
Labels: ⭐ goal: addition, size:S, lgtm

#306 Bugfix/283 remove dupes
  .gitignore
  backend/alembic.ini
  backend/alembic/README
  backend/alembic/env.py
  backend/alembic/script.py.mako
  backend/alembic/versions/6240656d52f6_add_job_title_column.py
  backend/alembic/versions/b240c664ed46_change_user_email_id_to_varchar.py
  backend/alembic/versions/c256d0279ea6_rename_user_email_table_to_plural.py
  backend/database.py
  backend/db/user_emails.py
  backend/db/utils/user_email_utils.py
  backend/requirements.txt
  backend/routes/email_routes.py
  backend/ruff.toml
  backend/tests/test_email_utils.py
  backend/utils/db_utils.py
  backend/utils/llm_utils.py
Labels: 🛠 goal: fix, size:XL, lgtm

#313 updated contributing
  .gitignore
  CONTRIBUTING.md
Labels: size:XS, lgtm

#308 Calculate response rate
  backend/main.py
  backend/routes/users_routes.py
Labels: ⭐ goal: addition, size:M, lgtm

#314 mis import
  backend/routes/users_routes.py
Labels: 🛠 goal: fix, 💻 aspect: code, size:S

#315 Feat/198 add posthog
  frontend/app/layout.tsx
  frontend/app/providers.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: ⭐ goal: addition, size:M

#317 update to gemini 2.0 flash lite
  backend/constants.py
  backend/routes/email_routes.py
  backend/utils/llm_utils.py
Labels: ✨ goal: improvement, size:S

#318 next steps should also be captured
  backend/email_query_filters/applied_email_filter.yaml
Labels: size:XS

#329 Redo homepage
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: ⭐ goal: addition, 🕹 aspect: interface, size:L

#330 display email processing progress on process page
  backend/routes/email_routes.py
  frontend/app/processing/page.tsx
Labels: ⭐ goal: addition, size:M, lgtm

#332 Redo homepage
  frontend/app/page.tsx
Labels: size:M

#324 fix dashboard
  frontend/app/dashboard/page.tsx
Labels: size:XS

#339 remove playground
  CONTRIBUTING.md
  backend/db/test_model.py
  backend/main.py
  backend/routes/playground_routes.py
  frontend/app/playground/page.tsx
Labels: 💻 aspect: code, size:L, lgtm

#335 Nadia/backend/email filter 2
  backend/config.py
  backend/email_query_filters/applied_email_filter.yaml
  backend/tests/test_constants.py
Labels: size:S, lgtm

#343 refactor hompage to use heroui components
  frontend/app/page.tsx
  frontend/components/icons.tsx
Labels: 💻 aspect: code, size:L, lgtm

#322 Add route protection
  backend/routes/auth_routes.py
  frontend/app/dashboard/page.tsx
  frontend/app/processing/page.tsx
  frontend/utils/auth.ts
Labels: ⭐ goal: addition, 🛠 goal: fix, size:L, lgtm

#331 321 feat display user flow via playground on homepage
  frontend/app/page.tsx
  frontend/app/preview/dashboard/page.tsx
  frontend/app/preview/processing/page.tsx
  frontend/components/navbar.tsx
  frontend/utils/mockData.ts
Labels: ⭐ goal: addition, size:XL

#336 Added Sankey Diagram Export
  backend/requirements.txt
  backend/routes/file_routes.py
  frontend/app/dashboard/page.tsx
Labels: ⭐ goal: addition, size:L, lgtm

#348 enlarge logo text and add bottom border to navbar
  frontend/components/navbar.tsx
Labels: 🕹 aspect: interface, size:XS, lgtm

#337 fetch email data from last timestamp
  backend/db/utils/user_utils.py
  backend/routes/auth_routes.py
  backend/routes/email_routes.py
Labels: ⭐ goal: addition, 🛠 goal: fix, size:M, lgtm

#345 [chore]: Refactor dashboard to use component
  frontend/app/dashboard/page.tsx
  frontend/app/page.tsx
  frontend/app/preview/dashboard/page.tsx
  frontend/app/success/page.tsx
  frontend/components/JobApplicationsDashboard.tsx
  frontend/public/sankey_diagram.png
  frontend/utils/auth.ts
  package-lock.json
Labels: 💻 aspect: code, size:XL

#344 Fix/168 error messaging scope change
  CONTRIBUTING.md
  backend/config.py
  backend/routes/auth_routes.py
  frontend/app/errors/page.tsx
Labels: 🛠 goal: fix, size:L

#360 add "remove" hover and remove job app modal
  frontend/components/JobApplicationsDashboard.tsx
  frontend/components/icons.tsx
Labels: ⭐ goal: addition, size:L

#248 User start date
  backend/constants.py
  backend/db/utils/user_utils.py
  backend/main.py
  backend/package-lock.json
  backend/requirements.txt
  backend/routes/auth_routes.py
  backend/routes/email_routes.py
  backend/routes/start_date_routes.py
  backend/start_date/storage.py
  backend/templates/processing.html
  backend/utils/auth_utils.py
  frontend/app/dashboard/page.tsx
  frontend/app/errors/page.tsx
  frontend/components/JobApplicationsDashboard.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/test-results/.last-run.json
  frontend/tests/dashboard.test.ts
  frontend/tests/success.test.ts
  package-lock.json
  package.json
Labels: ⭐ goal: addition, size:XL, lgtm

#346 Response rate frontend component
  backend/routes/users_routes.py
  frontend/app/error.tsx
  frontend/app/errors/page.tsx
  frontend/components/JobApplicationsDashboard.tsx
  frontend/components/icons.tsx
  frontend/components/response_rate_card.tsx
  frontend/components/response_rate_chart.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: ⭐ goal: addition, 🕹 aspect: interface, size:L, lgtm

#365 Add pagination to Job Applications table / Frontend / Adjust table component for pages (web)
  frontend/app/dashboard/page.tsx
  frontend/app/preview/dashboard/page.tsx
  frontend/components/JobApplicationsDashboard.tsx
Labels: ⭐ goal: addition, size:M

#193 chore: Configured permissions for 'pytest.yml' workflow (#165)
  .github/workflows/pytest.yml
Labels: 🤖 aspect: dx, size:S, lgtm
