Repository lnovitz/jobseeker-analytics, pull requests merged in 2025-02, with the labels that each got.

#157 Bugfix/155 fix local dev
  .gitignore
  CONTRIBUTING.md
  __init__.py
  backend/.env.example
  backend/__init__.py
  backend/auth_utils.py
  backend/config.py
  backend/config_utils.py
  backend/constants.py
  backend/llm_utils.py
  backend/main.py
  backend/requirements.txt
Labels: documentation, local environment

#163 Use CORSMiddleware to connect be and fe
  backend/main.py
  frontend/app/testpage/page.tsx
Labels: size:M, lgtm

#173 Created the Login with Google button in frontend and connected it to functionality
  backend/config.py
  backend/login/google_login.py
  backend/main.py
  backend/tests/test_config_utils.py
  frontend/.env.sample
  frontend/components/icons.tsx
  frontend/components/navbar.tsx
  frontend/utils/navbar-utils.ts
Labels: size:L, lgtm

#190 Homepage
  frontend/app/layout.tsx
  frontend/app/page.tsx
  frontend/components/navbar.tsx
  frontend/config/site.ts
  frontend/package-lock.json
  frontend/public/apple-touch-icon.png
  frontend/public/excel_ss.png
  frontend/public/favicon-96x96.png
  frontend/public/favicon.svg
  frontend/tailwind.config.js
Labels: 🕹 aspect: interface, size:L, lgtm

#174 Backend/bug/issue 72
  backend/constants.py
  backend/email_query_filters/applied_email_filter.yaml
  backend/email_query_filters/applied_email_filter_overrides.yaml
  backend/main.py
  backend/requirements.txt
  backend/tests/sample_base_filter.yaml
  backend/tests/test_constants.py
  backend/tests/test_filter_schema.py
  backend/tests/test_filter_utils.py
  backend/utils/email_utils.py
  backend/utils/filter_utils.py
Labels: size:XL, lgtm

#145 Precommit hooks to check frontend code
  frontend/.husky/pre-commit
  frontend/app/testpage/page.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: size:M

#187 chore: Pinned github jobs to hash version (#160)
  .github/workflows/ruff.yml
Labels: 🟨 P2 / severity: minor, 🤖 aspect: dx, help wanted, size:XS

#195 env file configurations
  .github/workflows/pytest.yml
  .gitignore
  backend/.env.example
  backend/config.py
  frontend/.env.sample
Labels: 🤖 aspect: dx, size:XS, lgtm

#196 Frontend code cleanup
  frontend/app/layout.tsx
  frontend/public/favicon.ico
  frontend/public/next.svg
  frontend/public/vercel.svg
Labels: 💻 aspect: code, size:XS, lgtm

#199 backend/dev iprovements
  CONTRIBUTING.md
  backend/Dockerfile
  backend/main.py
  docker-compose.yaml
Labels: 🛠 goal: fix, 🤖 aspect: dx, size:S, lgtm

#170 Create job_titles.py
  backend/db/job_titles.py
Labels: lgtm

#189 Processing page
  frontend/app/processing/page.tsx
  frontend/components/spinner.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: ✨ goal: improvement, 🕹 aspect: interface, size:M, lgtm

#207 add PR template
  .github/pull_request_template.md
Labels: 📖 aspect: docs, size:L

#208 Create CODE_OF_CONDUCT.md
  CODE_OF_CONDUCT.md
Labels: 📖 aspect: docs, size:L

#209 add template from ruby for good thx
  .github/ISSUE_TEMPLATE/bug_issue_template.yml
Labels: size:M

#210 add new feature request template thx ruby
  .github/ISSUE_TEMPLATE/feature_request_template.yml
Labels: size:M

#211 add docs template thx ruby
  .github/ISSUE_TEMPLATE/docs_issue_template.yml
Labels: size:M

#200 backend/bugfix/email-extraction
  backend/main.py
  backend/utils/email_utils.py
  backend/utils/llm_utils.py
Labels: 🛠 goal: fix, size:M, lgtm

#215 improve loading time by limiting lookback 90 days
  backend/constants.py
Labels: 🛠 goal: fix, size:XS

#218 fix login
  frontend/app/page.tsx
  frontend/components/navbar.tsx
Labels: 🛠 goal: fix, size:XS

#203 Navbar Tests PR
  frontend/tests/navbar.test.ts
Labels: 🕹 aspect: interface, size:M, lgtm

#201 Homepage Tests PR
  frontend/tests/homepage.test.ts
Labels: 💻 aspect: code, size:S

#206 Success Page Tests PR
  frontend/tests/success.test.ts
Labels: 🕹 aspect: interface, size:S, lgtm

#202 Login Tests PR
  frontend/tests/login.test.ts
Labels: 🤖 aspect: dx, size:S, lgtm
